### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by D-Sketon** [D-Sketon/hexo-theme-reimu#26]
- 新特性
  - [x] 版权提示 934454315de14ec42da49bbece8f4a3c75af5583
  - [x] 更好的复制代码 7da3a77f51b1ff517a1317fb90ad17aa8bef2db1
  - [x] 友链卡片优化 34e006c16b8dfe571c91cc212b938822a7f99312
  - [x] 外链卡片 04b17f98b5fdf74570f26b2bdc4366b3cd81ac16
- 性能优化
  - [x] 图片体积优化 ad8d0bb0c95d9de126e63f9891ea2e363fa4e9c5
  - [x] 探索字体体积优化 28183e77bf46291cd4c84081f50f4f96b1ce6303
  - [x] 懒加载js 23a065cd4663c43efdffdf2e3b3b5c269d3d7d01
  - [x] 探索移除jQuery https://github.com/D-Sketon/hexo-theme-reimu/pull/29
  - [x] 探索替换fancybox https://github.com/D-Sketon/hexo-theme-reimu/pull/27
  - [ ] 探索esbuild打包（长期）
